project:
  type: book

book:
  title: "Template for Quarto Book"
  cover-image: img/cover.jpg
  page-navigation: true
  author: "Steven S.T. Chiu (stchiu@tamu.edu)"
  date: today
  reader-mode: true
  favicon: img/TAMU-LogoBox.png
  chapters:
    - index.qmd
    - intro.qmd
    - ch1.qmd
    - hw/hw1.qmd
    - summary.qmd
    - ref.qmd
  navbar:
      background: maroon
      right:
        - icon: github
          href: https://github.com/stevengogogo/QuartoBook
      
bibliography: ref.bib

format:
  html:
    theme: 
      light: flatly
      dark: darkly





