project:
  type: book

book:
  title: "Template for Quarto Book"
  cover-image: img/cover.jpg
  page-navigation: true
  author: "Jane Doe"
  date: "8/25/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - hw/hw1.qmd
    - summary.qmd
    - ref.qmd

bibliography: ref.bib

format:
  html:
    theme: cosmo





