project:
  type: book

book:
  title: "Template for Quarto Book"
  cover-image: img/cover.jpg
  page-navigation: true
  repo-url:  https://github.com/stevengogogo/QuartoBook
  author: "Jane Doe"
  date: today
  favicon: img/favicon.png
  chapters:
    - index.qmd
    - intro.qmd
    - ch1.qmd
    - hw/hw1.qmd
    - summary.qmd
    - ref.qmd

bibliography: ref.bib

format:
  html:
    theme: 
      light: flatly
      dark: darkly





